AskAboutUpdating = true
AskBeforeExitingMetaMorpheus = false
AskAboutTopDownParams = true
AskAboutChymotrypsinParams = true
AskAboutElastaseParams = true
AskAboutNonSpecificParams = true
AskAboutSemiTrypsinParams = true
AskAboutArgCParams = true
AskAboutMBRParams = true
UseTopDownParams = true
UseChymotrypsinParams = true
UseElastaseParams = true
UseNonSpecificParams = true
UseSemiTrypsinParams = true
UseArgCParams = true
UseMBRParams = true
